### ISSUE TITLE
Reference to cite the algorithms and scripts

### ISSUE THREAD

**Issue by breylla** [SERVIR/water-quality-gee#1]
Hi!
I am preparing a research proposal that focus on tools to monitor water quality in lagoons and estuaries and I found these scripts. I would like to know the reference paper / manuscript you wrote, because I did not find the one that is on README.md
All the best!

**Comment by KMarkert** [comment]
Hi @breylla you can reference the following paper: https://doi.org/10.1016/j.rse.2019.111284 for the algorithms. We worked directly with Ben Page on translating the algorithm for use on GEE.

I hope this helps! All the best.

**Comment by breylla** [comment]
Hi @KMarkert !
Thank you very much.
